[package]
name = "dio"
version = "0.1.0"
authors = ["MovingtoMars <liam@bumblebee.net.nz>"]

[dependencies]
piston_window = "0.35.0"
gfx_device_gl = "0.8.2"
sdl2_mixer = "0.12.0"
sdl2 = "0.13.0"
lazy_static = "0.1.15"
ncollide_entities = "0.4.1"
ncollide_math = "0.2.2"
nalgebra = "0.6.0"
num = "0.1.31"

[dependencies.nphysics2d]
#features = [ "f64" ]
# path = "../nphysics"
git = "https://github.com/MovingtoMars/nphysics.git"
