[package]
name = "dio"
version = "0.1.0"
authors = ["MovingtoMars <liam@bumblebee.net.nz>"]

[dependencies]
piston_window = "0.35.0"
box2d = { version = "*", git = "https://github.com/MovingtoMars/rust_box2d" }
